{
 "title": "Traffic (ClickHouse)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Instant traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeInterval(time_flow_start) AS \"time\",\n    sum(bytes) AS bytes\nFROM flows_raw_view\nWHERE (time_flow_start >= $__fromTime AND time_flow_start <= $__toTime)\nGROUP BY time\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Top source IPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "WITH flows_agg AS (\n    SELECT\n        $__timeInterval(time_flow_start) AS \"time\",\n        src_addr,\n        sum(bytes) AS bytes\n    FROM flows_raw_view\n    WHERE (time_flow_start >= $__fromTime AND time_flow_start <= $__toTime)\n    GROUP BY time, src_addr\n)\nSELECT\n    \"time\",\n    src_addr,\n    bytes,\nFROM flows_agg\nWHERE src_addr IN (\n    SELECT src_addr\n    FROM flows_agg\n    GROUP BY src_addr\n    ORDER BY sum(bytes) DESC\n    LIMIT 10\n)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Top source ports",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "WITH flows_agg AS (\n    SELECT\n        $__timeInterval(time_flow_start) AS \"time\",\n        tuple(proto, src_port) AS port,\n        sum(bytes) AS bytes\n    FROM flows_raw_view\n    WHERE (time_flow_start >= $__fromTime AND time_flow_start <= $__toTime)\n    GROUP BY time, port\n)\nSELECT\n    \"time\",\n    port.1 || '/' || toString(port.2) as src_port_string,\n    bytes\nFROM flows_agg\nWHERE port IN (\n    SELECT port\n    FROM flows_agg\n    GROUP BY port\n    ORDER BY sum(bytes) DESC\n    LIMIT 10\n)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Top destination IPs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "WITH flows_agg AS (\n    SELECT\n        $__timeInterval(time_flow_start) AS \"time\",\n        dst_addr,\n        sum(bytes) AS bytes\n    FROM flows_raw_view\n    WHERE (time_flow_start >= $__fromTime AND time_flow_start <= $__toTime)\n    GROUP BY time, dst_addr\n)\nSELECT\n    \"time\",\n    dst_addr,\n    bytes,\nFROM flows_agg\nWHERE dst_addr IN (\n    SELECT dst_addr\n    FROM flows_agg\n    GROUP BY dst_addr\n    ORDER BY sum(bytes) DESC\n    LIMIT 10\n)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Top destination ports",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "WITH flows_agg AS (\n    SELECT\n        $__timeInterval(time_flow_start) AS \"time\",\n        tuple(proto, dst_port) AS port,\n        sum(bytes) AS bytes\n    FROM flows_raw_view\n    WHERE (time_flow_start >= $__fromTime AND time_flow_start <= $__toTime)\n    GROUP BY time, port\n)\nSELECT\n    \"time\",\n    port.1 || '/' || toString(port.2) as dst_port_string,\n    bytes\nFROM flows_agg\nWHERE port IN (\n    SELECT port\n    FROM flows_agg\n    GROUP BY port\n    ORDER BY sum(bytes) DESC\n    LIMIT 10\n)\nORDER BY time"
    }
   ]
  }
 ]
}