//go:build ignore
// +build ignore

package main

import (
	"log"
	"os"
	"text/template"
)

func main() {
	f, err := os.Create("all.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	entries, err := os.ReadDir("./")
	if err != nil {
		log.Fatal(err)
	}

	dirs := []string{}
	for _, e := range entries {
		if e.IsDir() {
			dirs = append(dirs, e.Name())
		}
	}
	allTemplate.Execute(f, struct {
		Dirs []string
	}{
		Dirs: dirs,
	})
}

var allTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
package enricher

import (
{{- range .Dirs }}
	_ "github.com/netsampler/goflow2/v2/transport/clickhouse/enricher/{{.}}"
{{- end }}
)
`))
