apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      host: clickhouse
      tlsSkipVerify: false

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
